Update Jenkins-ci

diff --git a/Jenkins-ci b/Jenkins-ci
--- a/Jenkins-ci
+++ b/Jenkins-ci
@@ -36,23 +36,25 @@ pipeline {
             steps {
                 echo '___Cleaning up old Docker images on remote server___'
                 sh '''
-                # Find containers using the image and remove them
-                IMAGE_ID=$(docker -H ssh://ubuntu@13.38.26.14 images --filter=reference='basmaoueslati/compare-appf25*' --format '{{.ID}}')
+                IMAGE_IDS=$(docker -H ssh://ubuntu@13.38.26.14 images --filter=reference='basmaoueslati/compare-appf25*' --format '{{.ID}}')
         
-                if [ -n "$IMAGE_ID" ]; then
-                  CONTAINERS=$(docker -H ssh://ubuntu@13.38.26.14 ps -a -q --filter ancestor=$IMAGE_ID)
-                  if [ -n "$CONTAINERS" ]; then
-                    echo "Stopping and removing containers using the image..."
-                    docker -H ssh://ubuntu@13.38.26.14 rm -f $CONTAINERS
-                  fi
+                for IMAGE_ID in $IMAGE_IDS; do
+                    echo "Processing image ID: $IMAGE_ID"
         
-                  echo "Removing image $IMAGE_ID..."
-                  docker -H ssh://ubuntu@13.38.26.14 rmi -f $IMAGE_ID
-                else
-                  echo "Image not found on remote server."
-                fi
+                    # Get containers based on the image
+                    CONTAINERS=$(docker -H ssh://ubuntu@13.38.26.14 ps -a -q --filter ancestor=$IMAGE_ID)
         
-                echo "Pruning dangling images..."
+                    if [ -n "$CONTAINERS" ]; then
+                        echo "Stopping and removing containers using image $IMAGE_ID"
+                        docker -H ssh://ubuntu@13.38.26.14 rm -f $CONTAINERS
+                    fi
+        
+                    # Attempt to remove the image
+                    echo "Removing image $IMAGE_ID"
+                    docker -H ssh://ubuntu@13.38.26.14 rmi -f $IMAGE_ID || echo "Could not remove image $IMAGE_ID"
+                done
+        
+                echo "Pruning dangling images"
                 docker -H ssh://ubuntu@13.38.26.14 image prune -f
                 '''
             }
