Update Jenkins-ci

diff --git a/Jenkins-ci b/Jenkins-ci
--- a/Jenkins-ci
+++ b/Jenkins-ci
@@ -36,26 +36,26 @@ pipeline {
             steps {
                 echo '___Cleaning up old Docker images on remote server___'
                 sh '''
-                IMAGE_IDS=$(docker -H ssh://ubuntu@13.38.26.14 images --filter=reference='basmaoueslati/compare-appf25*' --format '{{.ID}}')
+                IMAGE_IDS=$(docker -H ssh://ubuntu@15.188.146.236 images --filter=reference='basmaoueslati/compare-appf25*' --format '{{.ID}}')
         
                 for IMAGE_ID in $IMAGE_IDS; do
                     echo "Processing image ID: $IMAGE_ID"
         
                     # Get containers based on the image
-                    CONTAINERS=$(docker -H ssh://ubuntu@13.38.26.14 ps -a -q --filter ancestor=$IMAGE_ID)
+                    CONTAINERS=$(docker -H ssh://ubuntu@15.188.146.236 ps -a -q --filter ancestor=$IMAGE_ID)
         
                     if [ -n "$CONTAINERS" ]; then
                         echo "Stopping and removing containers using image $IMAGE_ID"
-                        docker -H ssh://ubuntu@13.38.26.14 rm -f $CONTAINERS
+                        docker -H ssh://ubuntu@15.188.146.236 rm -f $CONTAINERS
                     fi
         
                     # Attempt to remove the image
                     echo "Removing image $IMAGE_ID"
-                    docker -H ssh://ubuntu@13.38.26.14 rmi -f $IMAGE_ID || echo "Could not remove image $IMAGE_ID"
+                    docker -H ssh://ubuntu@15.188.146.236 rmi -f $IMAGE_ID || echo "Could not remove image $IMAGE_ID"
                 done
         
                 echo "Pruning dangling images"
-                docker -H ssh://ubuntu@13.38.26.14 image prune -f
+                docker -H ssh://ubuntu@15.188.146.236 image prune -f
                 '''
             }
         }
